function [value, flag, message] = solveATEs( eqnFcn, guess )
%solveATEs wrapper for solving algebraic-transcendental equations using
% fsolve
%   revised 11/9/17
%
%   eqnFcn = handle to a function that evaluates the equations (as 
%       residuals) given guesses for the values of the unknowns
%   guess = vector containing guesses for the values of the unknowns
%   value = vector containing the values of the unknowns
%   flag = integer exitflag returned by fsolve; if it is positive, the
%       equations were solved
%   message = Exit message generated by fsolve
    
    options = optimoptions('fsolve','Display','off');
    [value, ~, flag, details] = fsolve(eqnFcn,guess,options);
    message = details.message;

end % of solveATEs

